### ISSUE TITLE
How to get the file "../main.py"?

### ISSUE THREAD

**Issue by dingyitk159** [Ericzhang1/BAGAU-Net#1]
File "../main.py" will be running in the file "run.sh", but how can I get the code of file "../main.py"?

**Comment by Ericzhang1** [comment]
Thanks for your interest in our work. You are right. There is no 'main.py' in the repository. Instead, please use 'train.py' file as your 'main.py'. 'Run.sh' has already been modified.

**Comment by dingyitk159** [comment]
Thank you for your answer

**Comment by Ericzhang1** [comment]
issues solved
